### ISSUE TITLE
Exception on lambda in Python 2.7

### ISSUE THREAD

**Issue by adevore** [nvbn/py-backwards#1]
Lambdas fail to compile for the Python 2.7 target. I reduced a test case down to `lambda: None`. The traceback for me is:

```
> py-backwards -i lambda.py -t 2.7 -o compiled
Traceback (most recent call last):
  File "/home/adevore/.virtualenvs/py-backwards/bin/py-backwards", line 11, in <module>
    load_entry_point('py-backwards==0.3', 'console_scripts', 'py-backwards')()
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/main.py", line 27, in main
    const.TARGETS[args.target])
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/compiler.py", line 37, in compile_files
    _compile_file(paths, target)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/compiler.py", line 16, in _compile_file
    target)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/__init__.py", line 38, in transform
    transformer().visit(tree)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/yield_from.py", line 84, in visit
    return self.generic_visit(node)  # type: ignore
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/typed_ast/ast3.py", line 326, in generic_visit
    value = self.visit(value)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/yield_from.py", line 84, in visit
    return self.generic_visit(node)  # type: ignore
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/typed_ast/ast3.py", line 335, in generic_visit
    new_node = self.visit(old_value)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/yield_from.py", line 82, in visit
    node = self._handle_assignments(node)  # type: ignore
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/yield_from.py", line 61, in _handle_assignments
    index = self._get_yield_from_index(node, ast.Assign)
  File "/home/adevore/.virtualenvs/py-backwards/lib/python3.5/site-packages/py_backwards/transformers/yield_from.py", line 17, in _get_yield_from_index
    for n, child in enumerate(node.body):  # type: ignore
TypeError: 'Name' object is not iterable
```

**Comment by nvbn** [comment]
Does it work correctly with 0.4?

**Comment by adevore** [comment]
Yes, it completes successfully. Thanks!
